/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-05-24

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

//extern "C" {

/* Includes */
#include <stddef.h>
#include "BlueNRG_x_device.h"
#include "BlueNRG1_sysCtrl.h"
#include "BlueNRG1_gpio.h"
#include "factory.h"
#include "led.h"
/* Private typedef */

/* Private define  */

/* Private macro */

/* Private variables */
volatile uint32_t lSystickCounter=0;

/* Private function prototypes */

/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  uint32_t i1 = 0, i2 = 0, i3 = 0;

  Factory::getFactor().buildSystem();
  //Factory *test = new Factory;
  //test->buildSystem();

  /* TODO - Add your application code here */
  while (1)
  {
	  /*
	  if (i1>50000L) {
		  //test->checkButton(Bt1);
		  Factory::getFactor().checkButton();
		  i1=0;
	  }
	  //i1++;*/


	  /* Verifie le timestamp */

	  if (i1>500000L) {
		  Led::getLed(LED1).toggleLed();
		  i1=0;
	  }
	  if (i2>1000000L) {
		  Led::getLed(LED2).toggleLed();
		  i2=0;
	  }

	  /*if (i3>2000000L) {
		  Led::getLed(LED3).toggleLed();
		  i3=0;
	  }*/
	  i1++;
	  i2++;
	  //i3++;

  }
  return 0;
}
//}
